# Generated by Django 4.1.5 on 2023-01-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Имя записи", models.CharField(max_length=100)),
                ("Верхний HTML", models.FileField(upload_to="file/demand/")),
                ("Картинка", models.ImageField(upload_to="pictures/demand/")),
                ("Нижний HTML", models.FileField(upload_to="file/demand/")),
            ],
            options={
                "verbose_name": "DB Востребованность",
                "verbose_name_plural": "Страница Востребованность",
            },
        ),
        migrations.CreateModel(
            name="DataGeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Имя записи", models.CharField(max_length=100)),
                ("Верхний HTML", models.FileField(upload_to="file/geo/")),
                ("Картинка", models.ImageField(upload_to="pictures/geo/")),
                ("Нижний HTML", models.FileField(upload_to="file/geo/")),
            ],
            options={
                "verbose_name": "DB География",
                "verbose_name_plural": "Страница География",
            },
        ),
        migrations.CreateModel(
            name="DataMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Имя записи", models.CharField(max_length=100)),
                ("Верхний HTML", models.FileField(upload_to="file/main/")),
                ("Картинка", models.ImageField(upload_to="pictures/main/")),
                ("Нижний HTML", models.FileField(upload_to="file/main/")),
            ],
            options={
                "verbose_name": "DB Главная",
                "verbose_name_plural": "Главная страница",
            },
        ),
        migrations.CreateModel(
            name="DataRecVac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "DB Вакансии",
                "verbose_name_plural": "Страница Вакансии",
            },
        ),
        migrations.CreateModel(
            name="DataSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Имя записи", models.CharField(max_length=100)),
                ("Верхний HTML", models.FileField(upload_to="file/skills/")),
                ("Картинка", models.ImageField(upload_to="pictures/skills/")),
                ("Нижний HTML", models.FileField(upload_to="file/skills/")),
            ],
            options={
                "verbose_name": "DB Навыки",
                "verbose_name_plural": "Страница Навыки",
            },
        ),
    ]
