# Generated by Django 4.1.5 on 2023-01-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_datademand_имя записи_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datademand",
            name="Верхний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datademand",
            name="Картинка",
            field=models.ImageField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datademand",
            name="Нижний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datageo",
            name="Верхний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datageo",
            name="Картинка",
            field=models.ImageField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datageo",
            name="Нижний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="Верхний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="Картинка",
            field=models.ImageField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="Нижний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="dataskills",
            name="Верхний HTML",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="dataskills",
            name="Картинка",
            field=models.ImageField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="dataskills",
            name="Нижний HTML",
            field=models.FileField(upload_to="file/"),
        ),
    ]
