# Generated by Django 4.1.5 on 2023-01-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_datademand_верхний html_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datamain",
            name="Верхний HTML",
        ),
        migrations.RemoveField(
            model_name="datamain",
            name="Нижний HTML",
        ),
    ]
