# Generated by Django 4.1.5 on 2023-01-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_datamain_верхний html_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datamain",
            old_name="Картинка",
            new_name="pic_center",
        ),
    ]
