# Generated by Django 4.1.5 on 2023-01-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_картинка_datamain_pic_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="datamain",
            name="html_bot",
            field=models.FileField(null=True, upload_to="file/"),
        ),
        migrations.AddField(
            model_name="datamain",
            name="html_top",
            field=models.FileField(null=True, upload_to="file/"),
        ),
    ]
