# Generated by Django 4.1.5 on 2023-01-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_datamain_html_bot_datamain_html_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datademand",
            name="Верхний HTML",
            field=models.FileField(null=True, upload_to="file/demand/"),
        ),
        migrations.AlterField(
            model_name="datademand",
            name="Картинка",
            field=models.ImageField(null=True, upload_to="pictures/demand/"),
        ),
        migrations.AlterField(
            model_name="datademand",
            name="Нижний HTML",
            field=models.FileField(null=True, upload_to="file/demand/"),
        ),
        migrations.AlterField(
            model_name="datageo",
            name="Верхний HTML",
            field=models.FileField(null=True, upload_to="file/geo/"),
        ),
        migrations.AlterField(
            model_name="datageo",
            name="Картинка",
            field=models.ImageField(null=True, upload_to="pictures/geo/"),
        ),
        migrations.AlterField(
            model_name="datageo",
            name="Нижний HTML",
            field=models.FileField(null=True, upload_to="file/geo/"),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="html_bot",
            field=models.FileField(null=True, upload_to="file/main/"),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="html_top",
            field=models.FileField(null=True, upload_to="file/main/"),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="pic_center",
            field=models.ImageField(null=True, upload_to="pictures/main/"),
        ),
        migrations.AlterField(
            model_name="dataskills",
            name="Верхний HTML",
            field=models.FileField(null=True, upload_to="file/skills/"),
        ),
        migrations.AlterField(
            model_name="dataskills",
            name="Картинка",
            field=models.ImageField(null=True, upload_to="pictures/skills/"),
        ),
        migrations.AlterField(
            model_name="dataskills",
            name="Нижний HTML",
            field=models.FileField(null=True, upload_to="file/skills/"),
        ),
    ]
