# Generated by Django 4.1.5 on 2023-01-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_datamain_html_bot_alter_datamain_html_top_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamain",
            name="html_bot",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="file/main/"
            ),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="html_top",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="file/main/"
            ),
        ),
        migrations.AlterField(
            model_name="datamain",
            name="pic_center",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="pictures/main/"
            ),
        ),
    ]
